name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest  # Додаємо, якщо його немає в requirements.txt

      - name: Run tests
        run: pytest
        name: Simulate deploy
        if: success()  # Цей крок виконується тільки якщо попередній крок успішний
        run: |
          echo "Deployed"
